export const ADD_USER_TRADE = 'ADD_USER_TRADE'

export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const CURRENT_USER_RECEIVED = 'CURRENT_USER_RECEIVED'

export const GET_CURRENT_USER_LOCATION = 'GET_CURRENT_USER_LOCATION'

export const GET_ERRORS = 'GET_ERRORS'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const SHOW_TRADIE_MAP = 'SHOW_TRADIE_MAP'

export const SIGN_USER_UP = 'SIGN_USER_UP'

export const TRADE_ID = 'TRADE_ID'

export const TRADE_NAME = 'TRADE_NAME'

export const USER_CREATED = 'USER_CREATED'

export const USERS_RECEIVED = 'USERS_RECEIVED'